software-stack/lab: Remove inline html
open-education-hub/operating-systems pull request #108
Opened 2023-01-18 14:44 UTC by Alex-deVis

The use of inline html for labs leads to invalid paths on the website.
`.svg` files were updated to closely match the intended effect.

Signed-off-by: Alex Apostolescu <alexx.apostolescu@gmail.com>

2023-01-18 16:59 UTC, teodutu requested changes
I think I'm OK with this. The only issue I see with adjusting image sizes to fit our deployment is that they become less "generic" and other teachers might have a (slightly) harder time using them for their own classes. However, I believe this is a small price to pay for getting rid of those ugly (and broken) HTML links.

@razvand you proposed HTML links. Did you have anything else in mind?

2023-01-18 16:59 UTC, teodutu commented on content/chapters/software-stack/lab/content/modern-sw-stack.md
> +![Modern Software Stack](../media/modern-sw-stack-2.svg)
```suggestion
![Modern Software Stack](../media/modern-sw-stack.svg)
```

2023-01-19 09:08 UTC, teodutu approved these changes
Fine by me I guess. Let's see what @razvand has to say.

2023-01-23 16:38 UTC, razvand requested changes
@Alex-deVis, be sure to merge the two commits.

Not sure what is the issue with the `<img src ...` construct. It seems to be working for slides (see [here](https://github.com/open-education-hub/operating-systems/blob/master/content/chapters/app-interact/lecture/slides/classification.md#gitlab) - rendered [here](https://open-education-hub.github.io/operating-systems/Lecture/Application-Interaction/)). Is this something that has only to do with the lab content, not the slides?

2023-02-13 09:59 UTC, Alex-deVis commented
Hi, @razvand, you are right - this issue only affects lab content.

It has something to do with the paths where images are stored. In case of slides, the directory structure is the same - you still have a `media/` folder. In case of labs, all media is placed in `/assets/images`, so media paths have to be updated in the `.md`. The path is not updated for images referenced with inline html (`<img src="...">`) and thus the undefined references occur.

I think the best approach would be to give up on inline html and update size from the `.svg` itself.

2023-03-06 08:39 UTC, RazvanN7 approved these changes

2023-03-06 08:41 UTC, RazvanN7 commented
I'll just merge this so that the broken links are fixed. If there are other issues with this PR, we can address them in subsequent PRs.

2023-03-06 08:41 UTC, merged