io/lab: Explain the need for loops when using read/write
open-education-hub/operating-systems pull request #148
Opened 2023-02-16 08:31 UTC by Alex-deVis

Explain the need for loops when using `read()` and `write()` and remove manual quotations.

2023-02-27 05:28 UTC, teodutu requested changes
Just a few nits and then it'll be alright.

2023-02-27 05:28 UTC, teodutu commented on content/chapters/io/lab/content/file-descriptors.md
> +A return value between **0** and _bytes_to_read_ is not enough to decide whether we should stop reading.
```suggestion
The return value of `read()` may differ from `bytes_to_read` if there are not enough bytes available or if the operation is interrupted by a signal.
A return value between **0** and `bytes_to_read` is not enough to decide whether we should stop reading.
```

2023-02-27 05:28 UTC, teodutu commented on content/chapters/io/lab/content/file-descriptors.md
> +|     `"a+"`     |  `O_RDWR │ O_CREAT │ O_APPEND`  |
attaboy

2023-02-27 05:28 UTC, teodutu commented on content/chapters/io/lab/content/file-descriptors.md
> +
I would also add a link to [the "RETURN VALUE" section from `read()`'s man page](https://man7.org/linux/man-pages/man2/read.2.html#RETURN_VALUE)

2023-02-27 06:51 UTC, teodutu requested changes
One more take and it's done.

2023-02-27 06:51 UTC, teodutu commented on content/chapters/io/lab/content/file-descriptors.md
> +The [return value of `read()`](https://man7.org/linux/man-pages/man2/read.2.html#RETURN_VALUE) may differ from `bytes_to_read` if there are not enough bytes available or if the operation is interrupt
```suggestion
The [return value of `read()`](https://man7.org/linux/man-pages/man2/read.2.html#RETURN_VALUE) may be less than `bytes_to_read` if there are not enough bytes available or if the operation is interrupted by a signal.
```

2023-02-28 09:42 UTC, Alex-deVis commented
@teodutu, I applied your suggestion, this is ready to be squashed and merged.

2023-03-01 04:30 UTC, teodutu approved these changes

2023-03-01 04:30 UTC, merged