FIXES #115 Explain the write() system call
open-education-hub/operating-systems pull request #152
Opened 2023-02-26 09:17 UTC by andreia-oca

Add a paragraph to explain the `write()` syscall. Briefly mention file descriptors.

2023-02-26 09:35 UTC, Alex-deVis approved these changes

2023-02-27 03:12 UTC, teodutu requested changes
See my suggestions and then we can merge this.

2023-02-27 03:12 UTC, teodutu commented on content/chapters/software-stack/lab/content/basic-syscall.md
> +* `2` references the standard error (`stderr`)
```suggestion
- `0` references the standard input (`stdin`)

- `1` references the standard output (`stdout`)

- `2` references the standard error (`stderr`)
```

2023-02-27 03:12 UTC, teodutu commented on content/chapters/software-stack/lab/content/basic-syscall.md
> +For now, it is enough for you to know that:
```suggestion
For now, it is enough for you to know that they are integers that behave like file handlers.
The 3 most common file descriptors are: 
```

2023-02-28 07:52 UTC, teodutu approved these changes
I'm OK with this. Thanks!

2023-02-28 08:44 UTC, Alex-deVis approved these changes
If @teodutu approved it what else can I say?

2023-02-28 08:47 UTC, merged