Use `student@os` consistently as part of the prompt in code snippets
open-education-hub/operating-systems pull request #177
Opened 2023-03-13 03:18 UTC by razvand

Use `student@os` consistently as part of the prompt in code snippets.

2023-03-13 03:30 UTC, teodutu approved these changes

2023-03-13 03:38 UTC, teodutu requested changes
I approved this by mistake. The suggestion I made will only fix one linter error. `MD041` will be fixed by another PR. I created an issue about it: https://github.com/open-education-hub/operating-systems/issues/179.

2023-03-13 03:38 UTC, teodutu commented on content/chapters/io/lecture/demo/optimizations/README.md
>  This is a simple bash script that receives the port of a running server as argument and proceeds to run multiple **client.py** instances.
```suggestion
This is a simple bash script that receives the port of a running server as argument and proceeds to run multiple `client.py` instances.
```
To pacify the linter.

2023-03-13 03:40 UTC, razvand commented on content/chapters/io/lecture/demo/optimizations/README.md
>  This is a simple bash script that receives the port of a running server as argument and proceeds to run multiple **client.py** instances.
@teodutu, did.

2023-03-13 05:36 UTC, teodutu approved these changes
I'm OK with this. @razvand you decide if/how you want to squash the commits before merging.

2023-03-13 06:33 UTC, Alex-deVis approved these changes
@razvand, @teodutu, I am okay with merging it without the fix for `MD041`. We can address that in another PR.

2023-03-21 05:44 UTC, razvand commented
@Alex-deVis, @teodutu, I'm left only the `student@os` commits and I squashed them into a single one.

2023-03-21 05:53 UTC, merged