Update configuration for checkpatch
open-education-hub/operating-systems pull request #212
Opened 2023-03-20 19:54 UTC by razvand

Ignore warnings that are not relevant for the content.

2023-03-22 14:05 UTC, teodutu approved these changes

2023-03-23 06:17 UTC, Alex-deVis requested changes
Change the PR's title and commit message to: `infra/checkpatch: Update configuration`.

2023-03-23 21:38 UTC, gabrielmocanu commented
@razvand  Please rebase this PR.

2023-03-24 08:14 UTC, Alex-deVis approved these changes

2023-03-24 08:29 UTC, merged