infra/labeler: Fix pull request labeler workflow
open-education-hub/operating-systems pull request #224
Opened 2023-03-23 21:35 UTC by gabrielmocanu

- Switch to another GitHub action since the other didn't work with crontab / pull_request
- Update configuration file
- Fix add-labels script

2023-03-23 21:36 UTC, gabrielmocanu commented
You can see the tests that I made here: https://github.com/gabrielmocanu/operating-systems/pull/5

2023-03-24 02:56 UTC, teodutu requested changes
`doLabels` is too vague of a name. Why not `assignLabelsToPRs`? Other than this, I have faith (and nothing else) that this time it'll work.

2023-03-24 02:56 UTC, teodutu commented on .github/workflows/labeler.yml
> +            await doLabels({github, context})
```suggestion
            const { default: assignLabelsToPRs } = await import('${{ github.workspace }}/.github/scripts/add-labels.js') ;
            await assignLabelsToPRs({github, context})
```

2023-03-24 02:56 UTC, teodutu commented on .github/scripts/add-labels.js
> +export default async function doLabels({github, context})
```suggestion
export default async function assignLabelsToPRs({github, context})
```

2023-03-24 14:47 UTC, teodutu approved these changes
Godspeed! ☦

2023-03-24 14:47 UTC, gabrielmocanu commented
@Alex-deVis  Please approve it and merge it if it's OK.

2023-03-24 14:50 UTC, merged