Disable clang-format from super-linter
open-education-hub/operating-systems pull request #24
Opened 2022-11-01 17:14 UTC by razvand

Disable clang-format from super-linter

2022-11-01 19:10 UTC, teodutu requested changes
1. You made this branch from `Data_lab`, so you carried over the changes to the data lab to this PR.
2. Isn't this too drastic? I know our coding style isn't too compatible with the clang standard, but are they _that_ different that it requires disabling `clang-format` altogether?

2022-11-01 19:23 UTC, razvand commented
> 1. You made this branch from `Data_lab`, so you carried over the changes to the data lab to this PR.
> 2. Isn't this too drastic? I know our coding style isn't too compatible with the clang standard, but are they _that_ different that it requires disabling `clang-format` altogether?

1. Fixed.
2. See my update to the PR mesage.

2022-11-01 19:23 UTC, teodutu approved these changes
Given the additional details you provided, I now believe you're right to remove `clang-format`. `cpplint` should suffice for basic errors such as trailing whitespaces.

2022-11-10 08:07 UTC, RazvanN7 approved these changes

2022-11-10 11:09 UTC, lizababu approved these changes

2022-11-10 11:10 UTC, merged