infra: Disable build/include_subdir in CPPLINT.cfg
open-education-hub/operating-systems pull request #263
Opened 2023-04-05 20:28 UTC by razvand

This is a warning related to using a subdirectory when including a local header file. Unfortunately, this often gets to including `./test.h` which is ugly and uncommon. Disable it.

2023-04-05 20:29 UTC, Alex-deVis approved these changes

2023-04-06 04:34 UTC, teodutu requested changes
You should also update the makefile includes (`-I`) [1] to reflect this. We're currently `#include`-ing `utils/utils.h` for example [2].

[1] https://github.com/open-education-hub/operating-systems/tree/master/content/common/makefile
[2] https://github.com/open-education-hub/operating-systems/blob/8ca4f4858c31a342b2250ef58372cff9f062ea89/content/chapters/io/lab/support/pipes/anonymous_pipe.c#L10

2023-04-07 08:12 UTC, Alex-deVis commented
> You should also update the makefile includes (-I) [1] to reflect this. 

If i understand correctly, @razvand disables the requirement of a parent directory for including a header. So, both `#include "dir/foo.h"` and `"#include "foo.h"` should be valid.
If this is the case, is there any reason to change those files, @teodutu?

2023-04-08 03:15 UTC, teodutu approved these changes
It's merely for consistency. You generally want to just `#include "foo.h"` regardless of where `foo.h` is located. But you're right @Alex-deVis, we can leave things as they are. I'm approving this for convenience. @razvand, it's up to you to decide whether you want to change the generic makefiles and the `#include`s for the `utils/` files.

2023-05-04 07:09 UTC, teodutu commented
Too slow. Already implemented by #295.

2023-05-04 07:10 UTC, teodutu commented
Too slow. Already implemented by #295.

2023-05-04 07:10 UTC, closed without merging