Add warning to `benchmark_cp.sh`
open-education-hub/operating-systems pull request #265
Opened 2023-04-07 12:44 UTC by Iulian277

Added a note in the `benchmark_cp.sh` script to warn the users to run the script from local environment, because Docker container does not have permission to write to `/proc/sys/vm/drop_caches`. This PR resolves #261.

2023-04-07 12:53 UTC, gabrielmocanu commented
@Iulian277 

Please make a mention also into the [README](https://github.com/open-education-hub/operating-systems/blob/8ca4f4858c31a342b2250ef58372cff9f062ea89/content/chapters/data/lab/content/process-memory.md?plain=1#L538).

2023-04-07 16:26 UTC, gabrielmocanu commented
Great job!

Let's see if @teodutu  it's ok with this.

2023-04-08 04:21 UTC, teodutu requested changes
Before I approve this, I'd like to know why this can't be fixed from the container https://github.com/open-education-hub/operating-systems/issues/261#issuecomment-1500778655.

Either way, @Iulian277 squash your commits into a single one named "data/lab: Add warning about running `benchmark_cp.sh`", sign and add a description according to the `checkpatch.pl` errors [1]. 

[1] https://github.com/open-education-hub/operating-systems/actions/runs/4638821968/jobs/8209009276?pr=265

2023-04-08 04:21 UTC, teodutu commented on content/chapters/data/lab/content/process-memory.md
> +Run the script on local environment, not on Docker container.
```suggestion
Run the script in your local environment, not in the Docker container.
```

2023-04-08 04:21 UTC, teodutu commented on content/chapters/data/lab/support/copy/benchmark_cp.sh
> +# Docker container does not have permission to write to `/proc/sys/vm/_drop_caches`
```suggestion
# The Docker container does not have permission to write to `/proc/sys/vm/_drop_caches`
```

2023-04-09 08:06 UTC, closed without merging