io/lab: Explain UNIX sockets
open-education-hub/operating-systems pull request #282
Opened 2023-04-24 20:29 UTC by Alex-deVis

Stating the obvious won't hurt.
Closes #137.

2023-04-25 04:16 UTC, teodutu requested changes
In addition to my inline suggestions, you should squash your commits and add a description to satisfy checkpatch.

2023-04-25 04:16 UTC, teodutu commented on content/chapters/io/lab/content/beyond-network-sockets.md
> +UNIX sockets are a feature of POSIX-compliant operating systems (e.g. Linux, macOS) and are not available on non-POSIX operating systems such as Microsoft Windows.
```suggestion
UNIX sockets are a feature of POSIX-compliant operating systems (e.g. Linux, macOS) and are not available on non-POSIX operating systems, such as Microsoft Windows.
```

2023-04-25 04:16 UTC, teodutu commented on content/chapters/io/lab/content/beyond-network-sockets.md
> +However, there are third-party libraries providing similar features to UNIX sockets in non-POSIX systems, but they might not have the same performance and reliability.
It may be useful to provide an example.

2023-04-25 11:41 UTC, Alex-deVis commented
> In addition to my inline suggestions, you should squash your commits and add a description to satisfy checkpatch.

The checkpatch is satisfied.

2023-04-25 22:14 UTC, gabrielmocanu commented
![image](https://user-images.githubusercontent.com/34304856/234415897-b3159c42-fb72-458f-b781-c3f097e0d5f3.png)
Checkpatch right now

2023-04-26 07:43 UTC, teodutu approved these changes

2023-04-26 07:43 UTC, merged