compute/lab: Fix typos and punctuation
open-education-hub/operating-systems pull request #285
Opened 2023-04-30 10:47 UTC by teodorjuravlea

2023-04-30 11:34 UTC, teodutu requested changes
Thanks for the fixes. I only made a few suggestions, mainly regarding the spelling of bit-fields.

2023-04-30 11:34 UTC, teodutu commented on content/chapters/compute/lab/content/processes.md
> +This argument is actually a bit field containing more information than merely the exit code.
```suggestion
This argument is actually a bit-field containing more information than merely the exit code.
```
I've seen it written with a dash more than separately: https://en.cppreference.com/w/cpp/language/bit_field.

2023-04-30 11:34 UTC, teodutu commented on content/chapters/compute/lab/content/processes.md
> +You can view the rest of the information stored in the `status` bit field [in the man page](https://linux.die.net/man/2/waitpid).
```suggestion
You can view the rest of the information stored in the `status` bit-field [in the man page](https://linux.die.net/man/2/waitpid).
```
Ditto.

2023-04-30 11:34 UTC, teodutu commented on content/chapters/compute/lab/content/threads.md
> +Remember to use the appropriate [macros](https://linux.die.net/man/2/waitpid) for handling the `status` variable that is modified by `waitpid`, as it is a bit field.
```suggestion
Remember to use the appropriate [macros](https://linux.die.net/man/2/waitpid) for handling the `status` variable that is modified by `waitpid()`, as it is a bit-field.
```

2023-04-30 13:49 UTC, teodorjuravlea commented
Yeah, I've also looked quite a bit and couldn't find a definitive answer as to which spelling is correct. Either way, it is a bit more readable than "bitfield", so that's good.
I've added the suggestions.

2023-04-30 13:59 UTC, teodutu approved these changes
:+1:

2023-04-30 14:00 UTC, merged

2023-05-02 06:31 UTC, teodutu commented
@teodorjuravlea I've given you 5 SMLY for this PR. Keep up the good work!