app-interact/lab: Add quizzes to the os-cloud section #141
open-education-hub/operating-systems pull request #287
Opened 2023-04-30 14:25 UTC by mandrei12

2023-05-01 11:59 UTC, teodutu requested changes

2023-05-01 11:59 UTC, teodutu commented on content/chapters/app-interact/lab/quiz/http-post.md
Not good. This is aimed to be a 3rd-semester course. Students aren't expected to be knowledgeable of HTTP methods yet. Think of something else.

2023-05-17 16:12 UTC, gabrielmocanu commented
@mandrei12  bump on this

2023-05-20 12:22 UTC, mandrei12 commented on content/chapters/app-interact/lab/quiz/http-post.md
Since I could not come with a better quiz for this section I made sure to make another one regarding cgroups and namespaces in the other PR [1] .

[1]: https://github.com/open-education-hub/operating-systems/pull/286

2023-05-20 13:54 UTC, teodutu requested changes
Reword your commit message to `app-interact/lab: ...` and then we can merge this.

2023-05-24 04:46 UTC, gabrielmocanu commented
Can't we improvise another question?
It seems like a question for attention rather than learning something new.

@teodutu  our lord and savior, what do you think?

2023-05-24 04:49 UTC, teodutu commented
Yeah, agreed, but paying attention to some arguments may also be a legit question. @mandrei12 or @gabrielmocanu can you think of something else?

2023-10-03 09:32 UTC, merged