app-interact/lab: Add oneko as alternative to xeyes #142
open-education-hub/operating-systems pull request #288
Opened 2023-04-30 14:26 UTC by mandrei12

2023-05-01 11:48 UTC, teodutu requested changes
I reworded 2 paragraphs. You should also explain why that timer is needed. Its purpose is to delay the cat. You can verify this by running `while true; do kill -14 $(pidof oneko)`. You'll notice the cat is much faster in following your mouse. Add this detail to the exercise as a quiz that requires students to "hack" `oneko` themselves similarly to what I did.

2023-05-01 11:48 UTC, teodutu commented on content/chapters/app-interact/lab/content/arena.md
> +After running `oneko` under `strace`, we see communication on the Unix socket that is created at the beginning:
```suggestion
When running `oneko`, what differs from `xeyes` is the `SIGALRM` signal.
This means that `oneko` uses a timer, which is periodically set, and then it expires only to be reset again.

Verifying the communication between the X server and `oneko` is easy.
We see that the cat follows our mouse cursor, behaving similarly to `xeyes`.
After running `oneko` under `strace`, we see the communication uses the UNIX socket created at the beginning:
```

2023-05-17 16:12 UTC, gabrielmocanu commented
@mandrei12  bump on this

2023-05-20 09:47 UTC, teodutu requested changes
Squash your commits into a single one titled like so: `app-interact/lab: ...`

2023-05-20 13:44 UTC, gabrielmocanu approved these changes

2023-05-20 13:52 UTC, teodutu approved these changes

2023-05-20 13:53 UTC, merged