`compute/lab`: Added third argument for strtok_r in mini-shell.c
open-education-hub/operating-systems pull request #294
Opened 2023-05-02 16:33 UTC by teotiron

Hello,
I noticed that the `mini-shell.c` file used in the Arena subchapter of the Compute section had an issue regarding the calls to `strtok_r` used to parse input from the user which caused it to not compile. The calls only used 2 arguments, as if it was `strtok` which was called. I added the third parameter, `&saveptr`, in order to properly call `strtok_r`.

2023-05-03 05:17 UTC, cristian-vijelie approved these changes
Thanks for the fix

2023-05-03 05:20 UTC, cristian-vijelie requested changes
Please fix the problems pointed out by checkpatch
https://github.com/open-education-hub/operating-systems/actions/runs/4863564755/jobs/8682176935

2023-05-03 09:21 UTC, teodutu requested changes
@teotiron, as @cristian-vijelie pointed out, you need to edit your commit message to pacify `checkpatch.pl`. Run `git commit --amend -s`. This will open your default editor (probably nano or vim) and you'll be able to modify your commit message:

- change the title (first line) of the commit message to `compute/lab: Add ...`
- add a short description of your change (the one you provided in the PR should suffice: that `strtok_r()` takes 2 arguments, but only 2 were provided, thus the code didn't compile)
- the `-s` argument of the `git commit` command will add the `Signed-off-by` line for you.

Then run `git log` to make sure the commit message is alright. Finally, run `git push -f` to update the remote commit as well.

2023-05-04 06:22 UTC, gabrielmocanu approved these changes

2023-05-04 06:23 UTC, gabrielmocanu commented
LGTM

2023-05-04 06:23 UTC, teodutu approved these changes
:+1:

2023-05-04 06:24 UTC, merged