io/lab: Fix typos
open-education-hub/operating-systems pull request #308
Opened 2023-05-19 16:07 UTC by Tibi09

Fix found typos in io/lab.

2023-05-20 08:33 UTC, teodutu requested changes
Thanks for the fixes @Tibi09. I've made some extra corrections. Besides those, add a description to your commit message to pacify `checkpatch.pl` [1]. The `super-linter` failure is a false positive [2]. Let's skip it.

[1] https://github.com/open-education-hub/operating-systems/actions/runs/5026142993/jobs/9021452171?pr=308#step:7:48
[2] https://github.com/open-education-hub/operating-systems/actions/runs/5026142995/jobs/9021452166?pr=308#step:4:415

2023-05-20 08:33 UTC, teodutu commented on content/chapters/io/lab/content/beyond-network-sockets.md
> +When you're done, compile it first and then run `send_unix_socket`.
```suggestion
When you're done, compile the code and then run `send_unix_socket`.
```

2023-05-20 08:33 UTC, teodutu commented on content/chapters/io/lab/content/pipes.md
> +`send_fd_4` writes the flag to  file descriptor 4 (`pipefd[1]`), so the parent process needs to read it from from `pipedefd[0]`.
```suggestion
`send_fd_4` writes the flag to file descriptor 4 (`pipefd[1]`), so the parent process needs to read it from `pipedefd[0]`.
```

2023-05-20 19:02 UTC, Tibi09 commented
Thank you! I've added the corrections and the description. It should be fine now.

2023-05-20 19:21 UTC, Tibi09 commented
Found a bonus typo :smile:

2023-05-21 01:34 UTC, teodutu requested changes
You also need to sign-off your commit [1] like so `git commit --amend --signoff` and then force-push it once again. Make sure you have configured your username and email before signing the commit (`git config --global user.email your@email.com` and `git config --global user.name "Your Name"`).

[1] https://github.com/open-education-hub/operating-systems/actions/runs/5033759696/jobs/9030441388?pr=308

2023-05-22 06:19 UTC, teodutu approved these changes

2023-05-22 06:20 UTC, merged