workflows: Add PR deployment action
open-education-hub/operating-systems pull request #313
Opened 2023-07-10 08:00 UTC by teodutu

The action builds the rendered website and pushes it to the branch `gh-pages-pr` in a directory named after the last commit SHA. It then publishes a message containing the link where the website may be inspected.

2023-07-13 13:20 UTC, gabrielmocanu commented
Any way to test it?

2023-07-13 13:24 UTC, gabrielmocanu requested changes

2023-07-13 13:24 UTC, gabrielmocanu commented on .github/workflows/pr-deployment.yml
> +      - uses: actions/checkout@v2
```suggestion
      - uses: actions/checkout@v3
```

2023-07-13 13:24 UTC, gabrielmocanu commented on .github/workflows/pr-deployment.yml
> +          docker image list
```suggestion
```

2023-07-13 13:24 UTC, gabrielmocanu commented on .github/workflows/pr-deployment.yml
> +          user-email: teodor.dutu@gmail.com
Maybe use a bot account? I don't know, it might be overengineering.

2023-07-14 02:41 UTC, teodutu commented
> Any way to test it?

Yes, the PR itself. The action fails unfortunately.

2023-07-14 03:01 UTC, teodutu commented
I've made the changes you requested @gabrielmocanu. Let me know if you find a way to fix it.

2023-10-01 13:44 UTC, razvand commented
@teodutu , is this still relevant? Should we use the workflows in the [`actions`](https://github.com/open-education-hub/actions) repository?

2023-10-01 17:55 UTC, teodutu commented
Yes, it is relevant. We don't have such a workflow in the `actions` repo. It would be great if we did, but it's easier to validate it here. So I wish to get this working together with @VladNastase and whoever else may help and then move it to the `actions` repo to be used globally.

2023-10-01 19:11 UTC, razvand approved these changes
@teodutu , this looks good to me. Let's wait for @gabrielmocanu 's opinion and merge this as fast as possible.

2023-10-03 13:33 UTC, gabrielmocanu approved these changes

2023-10-03 16:21 UTC, merged