actions: Replace in-repo actions with separate repo
open-education-hub/operating-systems pull request #315
Opened 2023-07-29 02:13 UTC by teodutu

Storing GitHub actions inside the repo creates unnecessary duplicates across multiple repos. This issue is fixed by referring a centralised repo that stores actions as `.yml` files and basic configs.

2023-07-29 02:31 UTC, teodutu commented
@gabrielmocanu Running the labeller results in some 403s [1]. Should I keep some config files locally or something?
[1] https://github.com/open-education-hub/operating-systems/actions/runs/5698005800/job/15445395870?pr=315

2023-07-29 06:49 UTC, gabrielmocanu requested changes

2023-07-29 06:49 UTC, gabrielmocanu commented on .github/workflows/labeler.yml
> +  - content/chapters/software-stack/**/*
```suggestion
  - 'content/chapters/software-stack/**/*'
```

2023-07-29 06:49 UTC, gabrielmocanu commented on .github/workflows/labeler.yml
> +  - content/chapters/data/**/*
```suggestion
  - 'content/chapters/data/**/*'
```

2023-07-29 06:49 UTC, gabrielmocanu commented on .github/workflows/labeler.yml
> +  - content/chapters/compute/**/*
```suggestion
  - 'content/chapters/compute/**/*'
```

2023-07-29 06:49 UTC, gabrielmocanu commented on .github/workflows/labeler.yml
> +  - content/chapters/io/**/*
```suggestion
  - 'content/chapters/io/**/*'
```

2023-07-29 06:49 UTC, gabrielmocanu commented on .github/workflows/labeler.yml
> +  - content/chapters/app-interact/**/*
```suggestion
  - 'content/chapters/app-interact/**/*'
```

2023-07-29 06:49 UTC, gabrielmocanu commented on .github/workflows/labeler.yml
> +  - content/assignments/**/*
```suggestion
  - 'content/assignments/**/*'
```

2023-07-29 06:53 UTC, teodutu commented on .github/workflows/labeler.yml
> +  - content/chapters/software-stack/**/*
Why though? It was working just fine before.

2023-07-30 11:04 UTC, gabrielmocanu approved these changes

2023-07-30 12:07 UTC, merged

2023-10-07 17:22 UTC, PAN740623 commented on .github/workflows/labeler.yml
> +  - content/chapters/compute/**/*
更改

2023-10-07 17:23 UTC, PAN740623 commented on .github/workflows/labeler.yml
> +  - content/chapters/io/**/*
更改

2023-10-07 17:23 UTC, PAN740623 commented on .github/workflows/labeler.yml
> +  - content/chapters/app-interact/**/*
更改

2023-10-07 17:23 UTC, PAN740623 commented on .github/workflows/labeler.yml
> +  - content/assignments/**/*
更改

2023-10-07 17:23 UTC, PAN740623 commented on .github/workflows/labeler.yml
> +  - content/chapters/data/**/*
更改

2023-10-07 17:24 UTC, PAN740623 commented on .github/workflows/labeler.yml
> +  - content/chapters/software-stack/**/*
更改