asg/mem-alloc: Use doubly linked-list and update checker
open-education-hub/operating-systems pull request #325
Opened 2023-10-01 20:11 UTC by Alex-deVis

Add a pointer to prev in `struct block_meta` and move unmodifiable files to `utils/`.
Add memory leak checks and style checks to the checker.
Add `make check-fast` option to skip checking for memory leaks.
Add instructions for debugging with the VSCode debugger.

2023-10-02 13:22 UTC, razvand requested changes
Why is `checkpatch.pl` part of the repository. `checkpatch.pl` is to be used in conjunction with the Dockerfile as part of the [GitLab assignment repositor](). No need to add it here.

Ignore resulting executables in `snippets/`.

2023-10-02 13:22 UTC, razvand commented on content/assignments/memory-allocator/README.md
> +Total:                                                           100/100
The total has to be 90/100. Update the grading inside the tests.

2023-10-02 13:22 UTC, razvand commented on content/assignments/memory-allocator/README.md
> +If you want to run a single test, you give its name or its path as arguments to `run-tests.py`
```suggestion
If you want to run a single test, you give its name or its path as arguments to `run-tests.py`:
```

2023-10-02 19:46 UTC, Alex-deVis commented
> Ignore resulting executables in snippets/.

#TIL that you can write a `.gitignore` that ignores itself.

2023-10-04 12:39 UTC, Alex-deVis commented
@razvand bump on this

2023-10-04 13:26 UTC, teodutu commented
@razvand @Alex-deVis, thanks to @gabrielmocanu's arduous work, we can now render PRs that make changes to the website by adding the `needs-rendering` label. Use it whenever you need it. The action posts a comment with a link to the updated website.

2023-10-08 21:19 UTC, razvand approved these changes
All good.

2023-10-08 21:20 UTC, merged