compute: Update command to show expected output
open-education-hub/operating-systems pull request #345
Opened 2023-12-04 09:52 UTC by MekalBoy

Calling `strace -e clone ./sum_array_threads 2` would not show the clone3 syscall. Replacing `clone` with `clone,clone3` in both commands allows the syscalls to display as expected.

A small typo has also been fixed.

2023-12-04 13:08 UTC, teodutu requested changes
Thanks @MekalBoy. I suggested some inline fixes. Besides those, please reformat your commit description to 75 characters [1]. The super-linter failure is a false positive [2].

After this, please change the base branch of this PR to target `cs-pub-ro:main` instead of `open-education-hub:main`. The former repo is the one we're currently using and we'll push all updates from the latter into it at the end of the semester. Now to change the target, do the following:

```
# Add the `cs-pub-ro` repo as a remote
git remote add upb git@github.com:cs-pub-ro/operating-systems.git

# Feth the updates from the cs-pub-ro repo
git fetch upb

# Create a new branch that tracks cs-pub-ro:main
git check -b upb-main --track upb/main

# Move to the branch with the current fixes and rebase upb-main
git checkout computefix
git rebase -i upb-main
```

The last command will open your default editor with a list of commits. These are the extra commits from `cs-pub-ro:main` that haven't been integrated into `open-education-hub:main` yet. Change the word `pick` into `d` at the start of each line **apart from the last one**, which is the commit you're trying to make. Then save and exit. There should be no conflicts, but if there are any, fix them (they can only be line mismatches I think) and then run `git add <the files in this PR>` and then `git rebase --continue`. With or without conflicts, after the rebase is done, use `git push -f` to change your upstream branch, then open a new PR under the `cs-pub-ro` repo [3]. I'll close this one once the new PR is made.

[1] https://github.com/open-education-hub/operating-systems/actions/runs/7084827252/job/19279872877?pr=345#step:3:573
[2] https://github.com/open-education-hub/operating-systems/actions/runs/7084827252/job/19279872270?pr=345#step:3:694
[3] https://github.com/cs-pub-ro/operating-systems

2023-12-05 16:30 UTC, MekalBoy commented
Pull request for cs-pub-ro/operating-systems has been made here:
https://github.com/cs-pub-ro/operating-systems/pull/36

2023-12-05 16:30 UTC, MekalBoy commented on content/compute/lab/content/arena.md
> +student@os:~/.../lab/support/sum-array/c$ strace -e clone,clone3 rray_threads 2
Addressed in latest commit: https://github.com/open-education-hub/operating-systems/pull/345/commits/3e3f609f5d08022d0d9986b4ecba54bb28edf480

2023-12-05 16:30 UTC, MekalBoy commented on content/compute/lab/content/arena.md
> +student@os:~/.../lab/support/sum-array/c$ strace -e clone,clone3array_processes 2
Addressed in latest commit: https://github.com/open-education-hub/operating-systems/pull/345/commits/3e3f609f5d08022d0d9986b4ecba54bb28edf480

2023-12-05 22:14 UTC, closed without merging