[WIP] Data chapter
open-education-hub/operating-systems pull request #4
Opened 2022-02-10 07:49 UTC by RazvanN7

Adds the first exercice (sources + text) and a bit of the second exercice. This PR is supposed to add the entire Data chapter, each commit implementing a specific feature.

2022-08-23 13:56 UTC, RazvanN7 commented
To whom it may concern, currently you should just look at the `lecture` directory. The lab still needs some shaping.

2022-09-27 20:31 UTC, razvand requested changes
Add Makefile for slides (using `reveal-md`). See example from [the compute chapter](https://github.com/teodutu/operating-systems-oer/blob/compute-lecture/content/chapters/compute/lecture/Makefile).

2022-09-27 20:31 UTC, razvand commented on content/chapters/data/lecture/slides.md
> +    - demo/proc_pagemap
This appears twice. Is it correct?

2022-10-01 05:48 UTC, RazvanN7 commented on content/chapters/data/lecture/slides.md
> +    - demo/proc_pagemap
Yes.

2022-10-01 07:10 UTC, RazvanN7 commented
@razvand I added the Makefile, turned all images into svg and added quizzes. All that I need to do now is to split the course into subfiles.

2022-10-10 21:48 UTC, alexandruradovici commented on content/chapters/data/lecture/slides.md
> +    - `demo/variables/python_vars.d`
```suggestion
* D
    - `demo/variables/d_vars.d`
* Python
    - `demo/variables/python_vars.d`
```

2022-10-26 15:52 UTC, merged