workflows: Configure and disable Markdown linter options
open-education-hub/operating-systems pull request #48
Opened 2022-11-25 16:20 UTC by Alex-deVis

- Disable `MD024` to allow multiple headings with the same content
- Configure `MD033` to allow inline HTML img tags
- Disable `MD035` to allow the use of '----'
- Fixed markdownlinter errors on master.

2022-11-25 22:17 UTC, teodutu requested changes
Nice work! I left a few small comments.

In addition to those, there some more linter failures. Most of them are `MD104` failures for sentences like this one: `Bla bla: something`. `:` counts as a punctuation mark so what comes after it should be placed on a new line like this:
```
Bla bla:
something
```

Other errors that I noticed were triggered by certain keywords that `makrdownlint` wrongly expects to be placed between quotes, like "root", or "true". Just remove the corresponding lines from [this file](https://github.com/open-education-hub/operating-systems/blob/master/.github/workflows/rules/md101.js). While you do this, also look for other false positives, such as "false", in `md101.js` as well as in the rest of the `md*.js` files.

2022-11-25 22:17 UTC, teodutu commented on content/chapters/compute/lecture/slides/processes.md
> +<!-- markdownlint-disable MD051 -->
Ditto. Change the link below to point to `threads.md` instead.

2022-11-25 22:17 UTC, teodutu commented on content/chapters/compute/lecture/slides/scheduling.md
> +<!-- markdownlint-disable MD051 -->
Ditto.

2022-11-25 22:17 UTC, teodutu commented on content/chapters/software-stack/lab/quiz/common-functions.md
> +# Common functions
```suggestion
# Common Functions
```
In addition, each question should be in a separate file. But it's fine for now. We'll split them another time.

2022-11-25 22:17 UTC, teodutu commented on content/chapters/software-stack/lab/quiz/libc.md
> +## malloc
```suggestion
## `malloc()`
```

2022-11-26 18:55 UTC, Alex-deVis commented
I'll take a look at `MD101` and `MD104`.

> `:` counts as a punctuation mark so what comes after it should be placed on a new line

I would rather remove `:` from punctuation marks.

2022-11-26 19:15 UTC, teodutu commented
> > `:` counts as a punctuation mark so what comes after it should be placed on a new line
> 
> I would rather remove `:` from punctuation marks.

Yes, this would be the more sensible option.

2022-11-26 19:25 UTC, Alex-deVis commented
`MD104` considers URLs to be composed of multiple sentences because of `.` and `:` characters.
@razvand, @teodutu  is `.github/workflows/rules/md104.js` file downloaded or hand-written? If the latter is the case, I can add a check to skip URLs.

2022-11-26 19:57 UTC, teodutu commented
> @razvand, @teodutu is `.github/workflows/rules/md104.js` file downloaded or hand-written? If the latter is the case, I can add a check to skip URLs.

It's irrelevant whether downloaded or hand-written. Go ahead and skip URLs, then see if there are any more spurious errors.

2022-11-27 21:02 UTC, razvand approved these changes
Fantastic work, @Alex-deVis . Let's merge this ASAP.

@teodutu , are you OK with it, so we could merge it?

2022-11-27 21:07 UTC, teodutu approved these changes
I'm also OK with this. Squash it and merge it.

2022-11-27 21:09 UTC, merged