workflows: Add checkpatch.pl
open-education-hub/operating-systems pull request #86
Opened 2022-12-27 16:11 UTC by RaresCroicia

Fixes #68

Might need further changes since this is the default version of `checkpatch.pl`.

Signed-off-by: Rares Croicia <rarescroicia@gmail.com>

2022-12-27 17:05 UTC, teodutu reviewed
This looks good at first sight.

@RaresCroicia our existing coding style checks are handled by [`super-linter`](https://github.com/github/super-linter). Is there a way to add the `checkpatch.pl` as another `super-linter` check?

@razvand, do you think we should add some custom scripts or arguments to this PR, or leave it for the future? I'd say we can deal with this later and get this merged sooner.

2022-12-27 22:34 UTC, RaresCroicia commented
> Is there a way to add the `checkpatch.pl` as another `super-linter` check?

There should be, by adding the `Run checkpatch review` step in the `super-linter.yml`.
I am not sure if it works, that's why I am not pushing it yet to the PR. I will wait for an approval that this might/will work.

```yml
   .
   .
   .
   steps:
        - name: Checkout Code
          uses: actions/checkout@v3
          with:
            # Full git history is needed to get a proper list of changed files within `super-linter`
            fetch-depth: 0
  
        - name: Lint Code Base
          uses: github/super-linter@v4
          env:
            # Don't check already existent files
            VALIDATE_ALL_CODEBASE: false
            VALIDATE_GITHUB_ACTIONS: false
            VALIDATE_CLANG_FORMAT: false
            LINTER_RULES_PATH: /.github/workflows/
            MARKDOWN_CONFIG_FILE: config/config.json
            MARKDOWN_CUSTOM_RULE_GLOBS: rules/rules.js
            DEFAULT_BRANCH: master
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       - name: Run checkpatch review
          uses: webispy/checkpatch-action@v9
```

2022-12-28 16:00 UTC, teodutu commented
> > Is there a way to add the `checkpatch.pl` as another `super-linter` check?
> 
> There should be, by adding the `Run checkpatch review` step in `super-linter.yml`. I am not sure if it works, that's why I am not pushing it yet to the PR. I will wait for an approval that this might/will work.

It makes sense. @razvand should we merge this as it is?

2022-12-29 11:28 UTC, razvand commented
> > > Is there a way to add the `checkpatch.pl` as another `super-linter` check?
> > 
> > 
> > There should be, by adding the `Run checkpatch review` step in `super-linter.yml`. I am not sure if it works, that's why I am not pushing it yet to the PR. I will wait for an approval that this might/will work.
> 
> It makes sense. @razvand should we merge this as it is?

It doesn't make sense to add it as a rule to `super-linter.yml` as it's not connected to `super-linter`. In the ideally case, it would be `super-linter` calling `checkpatch`. Since this is not the case, a separate `checkpatch.yml` file is the way to go.

2022-12-29 11:29 UTC, razvand commented
> @razvand, do you think we should add some custom scripts or arguments to this PR, or leave it for the future? I'd say we can deal with this later and get this merged sooner.

Yes, let's do a minimal configuration for `checkpatch.pl` and then we can merge it. Lemme check what are good options.

2022-12-29 11:46 UTC, razvand commented
> > @razvand, do you think we should add some custom scripts or arguments to this PR, or leave it for the future? I'd say we can deal with this later and get this merged sooner.
> 
> Yes, let's do a minimal configuration for `checkpatch.pl` and then we can merge it. Lemme check what are good options.

@RaresCroicia , I recommend we used the following configuration in [`.checkpatch.conf`](https://github.com/webispy/checkpatch-action#checkpatchpl-configuration), based on [documentation](https://docs.kernel.org/dev-tools/checkpatch.html).

```text
# This isn't a Linux kernel tree.
--no-tree

# Show the message type in the output.
--show-types
```

I wouldn't add anything else. I think the default configuration options of `checkpatch.pl` are pretty sane.

2022-12-29 11:47 UTC, razvand commented
> it doesn't verify only the source codes

What do you mean by this?

2022-12-29 11:51 UTC, razvand requested changes
Please improve the commit message.

Use `workflows: Add checkpatch.pl as GitHub action for static checking`.

The add a descriptive message (after a blank line of the title message), telling about the addition of the `checkpatch.yml` and `.checkpatch.conf` files.

At the end, at the `Fixes #68` line.

2022-12-29 11:51 UTC, razvand commented on .github/workflows/checkpatch.yml
> +        fetch-depth: ${{ env.PR_FETCH_DEPTH }}
I would add the `Info` rule from [here](https://github.com/webispy/checkpatch-action/blob/master/.github/workflows/main.yml#L14).

2022-12-29 11:51 UTC, RaresCroicia commented
> > it doesn't verify only the source codes
> 
> 
> 
> What do you mean by this?

As you pointed in the issue, we want to use checkpatch for C source codes. Checkpatch verifies also the form of the commits, the messages etc., so I pointed that out.

2022-12-29 12:04 UTC, razvand commented
> > > it doesn't verify only the source codes
> > 
> > What do you mean by this?
> 
> As you pointed in the issue, we want to use checkpatch for C source codes. Checkpatch verifies also the form of the commits, the messages etc., so I pointed that out.

I find that useful. Leave it like that. More checks, healthier codebase and commit history.

2022-12-29 12:06 UTC, razvand commented
@RaresCroicia , be sure to credit, as part of the commit message, the source of the GitHub action config files: https://github.com/webispy/checkpatch-action

2022-12-29 12:26 UTC, razvand commented
@RaresCroicia  , once you make updates, use the `Resolve conversation` button to mark comments as solved. And then re-request reviews: top right, in the `Reviewers` area.

Also, be sure that checks are passed. And if not, that you have reasons for them not to require being passed.

2022-12-29 12:27 UTC, razvand commented
@RaresCroicia , you did a merge commit. I wonder why, I wonder how. Please use a single commit, use `git commit --amend` to amend an existing commit.

2022-12-29 13:03 UTC, razvand commented
@RaresCroicia , squash the two commits, we only need one commit.

2022-12-29 14:59 UTC, RaresCroicia commented
I messed up with a merge (I clicked sync on the wrong branch on my fork by mistake)
I reset the branch to the last one i've done, and remade the commits. 
I hope I didn't mess up again with anything.

2022-12-29 15:12 UTC, razvand requested changes
See my comments. Update the commit description to:

```
Set `checkpatch.pl` GitHub action (https://github.com/webispy/checkpatch-action) for pull requests. Add `checkpatch.yml` file to configure workflow and and `.checkpatch.conf` to configure `checkpatch.pl`.
```

2022-12-29 15:12 UTC, razvand commented on .checkpatch.conf
> +--ignore NEW_TYPEDEFS
And ending newline.

2022-12-29 15:12 UTC, razvand commented on .checkpatch.conf
> +
```suggestion

# Emit diffed file position, not input file position.
--showfile

```

2022-12-29 16:08 UTC, razvand approved these changes
@RaresCroicia , I approved this. Before we merge it, please wrap the commit description to 72 or 80 characters. You needn't have a single long line per-sentence.

2022-12-29 16:18 UTC, RaresCroicia commented
All done!

2022-12-29 16:26 UTC, merged