{data,software-stack}/lab: Update `ltrace` usage
open-education-hub/operating-systems pull request #94
Opened 2023-01-03 20:59 UTC by mariasfiraiala

On some systems (such as the SO VM), `ltrace` results in empty outputs for binaries that otherwise make library calls. This is due to `now binding` and affects even system binaries, such as `ls` and `pwd`.

This PR forces the `lazy binding`, by modifying the `LDFLAGS` in Makefiles, and warns students about the potentially missing output for system executables.

Lab files that mention the `ltrace` function are:

```console
maria@ssshadows:~/Documents/school-work/git-stuff/operating-systems.git/content/chapters$ grep -nr "ltrace"
software-stack/lab/quiz/high-level-lang.md:9:- `ltrace`
software-stack/lab/quiz/libs.md:11:+ `ltrace`
software-stack/lab/quiz/libs.md:23:`ltrace` and `ldd` are used to capture connections to dynamic libraries.
software-stack/lab/content/app-investigate.md:45:1. Use `ltrace` and `strace` on the two applications.
software-stack/lab/content/libcall-syscall.md:13:Let's build the program and then trace the library calls (with `ltrace`) and the system calls (with `strace`):
software-stack/lab/content/libcall-syscall.md:22:student@os:~/.../lab/support/libcall-syscall$ ltrace ./call
software-stack/lab/content/libcall-syscall.md:57:   Use `ltrace` and `strace`.
software-stack/lab/content/arena.md:89:   Use `ltrace` and `strace` to compute the number of library calls and system calls.
software-stack/lab/content/arena.md:102:   Use `ltrace` and `strace` to compute the number of library calls and system calls.
software-stack/lab/content/arena.md:117:1. Run `ldd`, `nm`, `strace`, `ltrace` on a statically-linked application executable.
software-stack/lab/content/high-level-lang.md:19:student@os:~/.../lab/support/high-level-lang$ ltrace -l 'libc*' python hello.py 2> libc.out
software-stack/lab/content/high-level-lang.md:100:   Use `ltrace` and `strace` to compute the number of library calls and system calls.
data/lab/content/investigate-memory.md:228:1. Use `ltrace` to list `malloc()` and `free()` calls made by the investigated system executables.
data/lab/content/process-memory.md:458:Run the executable under `ltrace` and `strace`:
data/lab/content/process-memory.md:461:student@os:~/.../lab/support/alloc_size$ ltrace ./alloc_size
data/lab/content/process-memory.md:492:Rebuild the program and rerun it under `ltrace` and `strace`:
data/lab/content/process-memory.md:495:student@os:~/.../lab/support/alloc_size$ ltrace ./alloc_size
```

Signed-off-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

2023-01-05 08:50 UTC, teodutu requested changes
Thanks for the fix. Apart from my inline comments, consider adding [this link](http://www.qnx.com/developers/docs/qnxcar2/index.jsp?topic=%2Fcom.qnx.doc.neutrino.prog%2Ftopic%2Fdevel_Lazy_binding.html) inside `libcall-syscall.md` to explain the differences between now binding and lazy binding.

2023-01-05 08:50 UTC, teodutu commented on content/chapters/data/lab/content/investigate-memory.md
> +Fear not, you can always check the library calls with a more verbose and harder to parse `ltrace` command:
Me love some passive-aggressiveness :heart:.

2023-01-05 08:50 UTC, teodutu commented on content/chapters/data/lab/content/investigate-memory.md
> +Note that, as explained in the [`software-stack` lab](https://open-education-hub.github.io/operating-systems/Lab/Software-Stack/Libcall-Syscall/content/libcall-syscall), on some systems, `ltrace` doe
```suggestion
Note that, as explained in the [Software Stack lab](https://open-education-hub.github.io/operating-systems/Lab/Software-Stack/Libcall-Syscall/content/libcall-syscall), on some systems, `ltrace` does not accurately show the output, due to _now binding_.
```

Backticks should be only used for code.

2023-01-05 08:50 UTC, teodutu commented on content/chapters/software-stack/lab/content/libcall-syscall.md
> +An example can be found in `support/libcall-syscall/Makefile`, however for system binaries, such as `ls` or `pwd`, the only alternative is:
```suggestion
An example can be found in `support/libcall-syscall/Makefile`, however for system binaries, such as `ls` or `pwd`, the only alternative is to add the `-x "*"` argument to force the command to trace all symbols in the symbol table:
```

2023-01-05 08:50 UTC, teodutu commented on content/chapters/software-stack/lab/content/libcall-syscall.md
> +student@os:~$ ltrace -x "*"
```suggestion
student@os:~$ ltrace -x "*" ls
```

2023-01-05 08:50 UTC, teodutu commented on content/chapters/software-stack/lab/content/libcall-syscall.md
> +
I would add some text and a command-line snippet saying that if one only wants to trace certain known symbols, they can use `-x "malloc" -x "free"` etc.

2023-01-05 08:50 UTC, teodutu commented on content/chapters/software-stack/lab/content/libcall-syscall.md
> +Note that on some systems, `ltrace` **does not work** as expected, due to `now binding`.
```suggestion
Note that on some systems, `ltrace` **does not work** as expected, due to **now binding**.
```

2023-01-05 18:28 UTC, mariasfiraiala commented
@teodutu I've changed the wording and styling as per your suggestion. I haven't added the link you provided as I can't tell what lazy binding or now binding are from accessing it; it shows something related to BlackBerry QNX and Embedded Systems.

Take another glance at this PR when you have some spare time.

2023-01-05 20:49 UTC, teodutu commented
The changes are fine now. Sorry about the link, I pasted something wrong. This one is what I had in mind: https://maskray.me/blog/2021-09-19-all-about-procedure-linkage-table. Add it to the Markdown file and we can merge this.

2023-01-05 21:03 UTC, mariasfiraiala commented
Done @teodutu. Nice link, I did some searching myself and I didn't find this one.

2023-01-05 21:29 UTC, teodutu requested changes
Nearly there.

2023-01-05 21:29 UTC, teodutu commented on content/chapters/software-stack/lab/content/libcall-syscall.md
> +If you would like to know more about **lazy binding**, **now binding** or **PLT** entries, check out [the documentation](https://maskray.me/blog/2021-09-19-all-about-procedure-linkage-table).
```suggestion
If you would like to know more about **lazy binding**, **now binding** or **PLT** entries, check out [this blog post](https://maskray.me/blog/2021-09-19-all-about-procedure-linkage-table).
```
It's not really documentation.

2023-01-06 08:39 UTC, mariasfiraiala commented
Fixed it @teodutu .

2023-01-06 09:03 UTC, teodutu approved these changes
:ok_hand:

2023-01-06 09:03 UTC, merged